name: 'kisan_krushi'
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  file_picker: ^10.3.2
  image_picker: ^1.2.0
  flutter_sound: ^9.28.0
  permission_handler: ^12.0.1
  record: ^6.1.1
  path_provider: ^2.1.5
  foundation: ^0.0.5
  flutter_tts: ^4.2.3
  firebase_auth: ^6.0.2
  google_sign_in: ^7.1.1
  cloud_firestore: ^6.0.1
  firebase_core: ^4.1.0
  geolocator: ^10.1.0
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.7.0
  geocoding: ^2.2.0
  flutter_local_notifications: ^19.4.2
  provider: ^6.1.5+1
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.1
  youtube_player_flutter: ^9.1.2
  speech_to_text: ^7.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   # <-- Added here


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo3.png"



flutter:
  assets:
    - assets/logo.png
    - assets/logo1.png
    - assets/logo2.jpg
    - assets/logo3.png
    - assets/profile.png

  uses-material-design: true



