// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvJdgJ9W3Y19gqf90eB8ovhHj9_JsxRbQ',
    appId: '1:871545668684:android:2ee5c83b7aa979e1d7e0e9',
    messagingSenderId: '871545668684',
    projectId: 'maha-krushi-mittra',
    storageBucket: 'maha-krushi-mittra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfG6drgtcErY4efxcXQLo7R73PbflI0j4',
    appId: '1:871545668684:ios:cd27fc67dba476e6d7e0e9',
    messagingSenderId: '871545668684',
    projectId: 'maha-krushi-mittra',
    storageBucket: 'maha-krushi-mittra.firebasestorage.app',
    iosClientId: '871545668684-pc90lorciqcp8blcqgfmg4o1d2u30ppl.apps.googleusercontent.com',
    iosBundleId: 'com.example.mahaKisanKrushi',
  );
}
